### PR TITLE
Rewrite MongoDB and Cassandra compensations tests

### PR DESCRIPTION
**Pull request by gytis**
I've replaced MongoDB and Cassandra tests with the similar test from our MongoDB quickstart. It doesn't use internal classes.

### CODE REVIEW

**Comment by scottmarlow** [comment]
Works for me but I did see a few failures that went away the second time that I ran the tests.  Maybe this has to do more with problems in the wildfly/testsuite/nosql tests in general.  http://pastebin.com/eFsy13hs has some output.

**Comment by scottmarlow** [comment]
hmm, could be my environment, I just noticed some local auth failures with MongoDB

**Comment by gytis** [comment]
The log contains failures in other tests too, so I guess it's your local environment.

**Comment by scottmarlow** [comment]
I agree, it must be local to my machine environment.  Merged.

**Pull request closed without merging**
